### ISSUE TITLE
Misuse of c.info() in JsMacroImpl

### ISSUE THREAD

**Issue by jdrphillips** [playframework/play-json#87]
Specifically here: https://github.com/playframework/play-json/blob/master/play-json/shared/src/main/scala/JsMacroImpl.scala#L243

If you have a case class with an apply method of the same arity as the primary constructor, this code logs an `INFO` statement during compilation.

However, the docs specify that `c.info` should represent a warning, not an `INFO` statement (http://docs.scala-lang.org/overviews/macros/overview.html#reporting-warnings-and-errors)

Having multiple apply methods of the same arity is fine, and should not be warned against.

**Comment by marius-carp** [comment]
:+1:

**Comment by giulio-sefaira** [comment]
👍

**Comment by gmethvin** [comment]
Interesting. That doc seems to contradict what the [scaladoc](http://www.scala-lang.org/api/2.12.x/scala-reflect/scala/reflect/macros/FrontEnds.html#info(pos:FrontEnds.this.Position,msg:String,force:Boolean):Unit) says: 
>  Emits an informational message, suppressed unless `-verbose` or `force=true`. Use `enclosingPosition` if you're in doubt what position to pass to `pos`.

The original code actually did actually warn unintentionally and that was fixed in #74 (2.6.1). Would be happy to accept a PR if you have a better solution, though.

**Comment by retronym** [comment]
Fixing the documentation in https://github.com/scala/scala.github.com/pull/842

**Comment by jdrphillips** [comment]
Thanks @gmethvin and @retronym - I guess that does resolve this issue, but the next one is regarding @gmethvin 's quote:

> Emits an informational message, **suppressed unless -verbose or force=true**.

In our project we do not set the `-verbose` flag and `force=false` is set in the play code, but we still get the `INFO` statements during compilation. Is this another documentation issue or a bug that should be raised with scala do you think?
